- name: Build Xcode Project
        run: |
          # On cherche où est le fichier .xcworkspace exactement
          WORKSPACE_PATH=$(find ios -name "*.xcworkspace" | head -n 1)
          echo "Workspace trouvé : $WORKSPACE_PATH"
          
          xcodebuild -workspace "$WORKSPACE_PATH" \
                     -scheme App \
                     -configuration Debug \
                     -sdk iphoneos \
                     -destination 'generic/platform=iOS' \
                     -archivePath App.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO